Models
Regilios/Java_Pet pull request #1
Opened 2024-11-10 10:49 UTC by Regilios

2024-11-10 11:37 UTC, MaximBezpalchuk requested changes

2024-11-10 11:37 UTC, MaximBezpalchuk commented on pom.xml
> +            <groupId>org.thymeleaf</groupId>
Зачем?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on pom.xml
> +            <artifactId>spring-webmvc</artifactId>
Зачем?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on pom.xml
> +            <groupId>jakarta.servlet</groupId>
Зачем?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/CheckFunction.java
> +    public void startCheck() {
Зачем?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/CheckFunction.java
> +    public List<Lecture> getTimetableDay(Teacher teacher, LocalDate localDate) {
Именование некорректно. Впрямую перевод "дай расписание день". getTimetable более чем достаточно, сигнатура метода дальше показывает, by какие характеристики отдать результат

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/CheckFunction.java
> +    public List<Lecture> getTimetableDay(Student student, LocalDate localDate) {
Почему getTimetable, а возвращает list<Lecture>? Или DTO "Timetable" или меняй именование

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/CheckFunction.java
> +        return lection_list.stream().filter(lecture -> lecture.getLocalTimeStart().getDayOfMonth() == localDate.getDayOfMonth()).collect(Collectors.toList());
Перед return перенос строки. Строка слишком длинная - используй ctrl+alt+L

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/CheckFunction.java
> +public class CheckFunction {
Не понимаю смысла класса в контексте приложения

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/CheckFunction.java
> +        return lection_list.stream().filter(lecture -> lecture.getLocalTimeStart().getDayOfMonth() == localDate.getDayOfMonth()).collect(Collectors.toList());
Сама функция - неоптимальна. Ты грузишь сервер, медленную джаву, в то время как это же условие ты мог задать в быстром sql

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/formatter/Formatter.java
> +    public String formatListGroup(List<Group> list) {
formatGroupList

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/formatter/Formatter.java
> +    private final String COL = "  |  ";
Почитай как объявляются константы

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/formatter/Formatter.java
> +        int maxColCathedra = getMaxCol(list, Lecture::getCathedraName);
почему пользуешься примитивами? Есть особенная необходимость?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/formatter/Formatter.java
> +                "ID: %-3s" +
Удобнее описать функцией (функциональный класс Function) отдельно, используя StringBuilder

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/interfaces/DaoAudienceInterfaces.java
> +public interface DaoAudienceInterfaces extends DaoInterfaces<Audience>{
почему Intrerfaces? Он внутри себя содержит множество интерфейсов?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/interfaces/DaoStudentInterfaces.java
> +     List<Student> findAllStudentByIdGroup(Group group);
byGroupId

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/interfaces/DaoTeacherInterfaces.java
> +    void teacherAppointSubject(Long teacher_id, Long subject_id);
Почему нижние подчеркивания?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/interfaces/DaoTeacherInterfaces.java
> +    void teacherAppointSubject(Long teacher_id, Long subject_id);
Что метод делает? Не понимаю из названия. Назначить учителю вести новый предмет? appointSubject? addSubject?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/interfaces/DaoTeacherInterfaces.java
> +    void deleteTeacherToSubject(Long teacher_id, Long subject_id);
Внутрянка не интересует - то, что у тебя это может быть реализовано в отдельной таблице многие-ко-многим не должно отражаться на функции. Ты удаляешь связь учитель-предмет. Находять в интерфейсе для УЧИТЕЛЯ, достаточно написать removeSubject как антоним addSubject

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/models/Audience.java
> +    private Integer room;
RoomNumber. Иначе ожидаю увидеть сущность Room

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/models/Audience.java
> +    private Integer size;
Скорее уж capacity, ибо size - характеристика физического размера, аля 2х2 метра

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/jdbc/JdbcAudience.java
> +    public void create(Audience audience) {
возвращай id созданной записи. Общепринятые нормы, твой кейхолдер именно поэтому умеет это делать. Выводить этот id или сохранять его в какую-то переменную при этом не надо. Кому надо - сохранит

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/jdbc/JdbcCathedra.java
> +    private static final String SQL_CREATE = "INSERT INTO cathedra (name) VALUES (?)";
лишний пробел перед (name)

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/jdbc/JdbcGroup.java
> +            throw new IllegalArgumentException("Группа с таким id не существует или не найден!");
Некорректный текст ошибки. Ты не ищешь в БД группу с id=null. По сути ты описываешь текстом NPE - так и опиши, что такие айдишники недопустимы

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/jdbc/JdbcGroup.java
> +    public void deleteGroupToLEction(Long group_id, Long lection_id) {
Опечатка. Идея с To та же самая, что и выше. Не буду для однотипных мест повторяться

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/jdbc/JdbcAudience.java
> +    private static final String SQL_GET_BY_ID = "SELECT * FROM audience WHERE id = ?";
Почему именования стартуют с SQL? Что мешает назвать BY_ID?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/formatter/Formatter.java
> +public class Formatter {
Почему форматтер внутри слоя работы с data access object?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/models/Audience.java
> +public class Audience implements Serializable {
модели в dao? Тут только интерфейсы работы с БД, их имплементации и максимум мапперы

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/mapper/HolidayMapper.java
> +        holiday.setEndHoliday(rs.getDate("end_holiday").toLocalDate());
потенциальный NPE. Если в БД у записи не указана дата конца праздника? (как вариант) - ты запрашиваешь сразу toLocalDate.

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/main/java/org/example/univer/dao/mapper/LectureMapper.java
> +        if (!rs.wasNull()) {
Посмотри каким образом у resultSet обновляется boolean wasNull. Корректно ли в таком случае использовать этот метод так?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/test/java/org/example/univer/test/JdbcAudienceTest.java
> +    @Autowired
переносы строк?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/test/java/org/example/univer/test/JdbcAudienceTest.java
> +    void checkUpdateTeacher() {
А где апдейт в БД? Ты проверяешь, что сеттер java работает или jdbc?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/test/java/org/example/univer/test/JdbcAudienceTest.java
> +        assertEquals(jdbcAudience.findById(1L), audience);
А тут что за прикол? Ты воде пишешь в названии метода одно, а потом проверяешь...что с чем? Один и тот же java-объект, в чем прикол?

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/test/java/org/example/univer/test/JdbcAudienceTest.java
> +package org.example.univer.test;
Заверни в папку jdbc

2024-11-10 11:37 UTC, MaximBezpalchuk commented on src/test/java/org/example/univer/test/JdbcVacationTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
Для чего это надо понимаешь? Аналог без аннотации сможешь сделать?

2024-11-13 16:31 UTC, MaximBezpalchuk commented on README.md
> +<<<<<<< HEAD
Тестовое сообщение для Кирилла

2024-11-13 16:33 UTC, Regilios commented on src/main/java/org/example/univer/dao/formatter/Formatter.java
> +        int maxColCathedra = getMaxCol(list, Lecture::getCathedraName);
Использование. Как мы видели, примитивные типы намного быстрее и требуют гораздо меньше памяти. Поэтому мы можем предпочесть их использование .

2024-11-13 16:33 UTC, Regilios commented on src/main/java/org/example/univer/dao/formatter/Formatter.java
> +                "ID: %-3s" +
Вообще не понял про что речь, поясни. Что именно описать отдельной функцией?

2024-11-13 16:33 UTC, Regilios commented on src/main/java/org/example/univer/dao/mapper/HolidayMapper.java
> +        holiday.setEndHoliday(rs.getDate("end_holiday").toLocalDate());
не понял, разъясни

2024-11-13 16:33 UTC, Regilios commented on src/test/java/org/example/univer/test/JdbcVacationTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
1. связываем Junit с Spring чтобы тот мог с ним работать.
2. подрубаем конфиги.
3. сбрасывем контекст после каждого теста.
Про аналог не понял.

2024-11-13 16:33 UTC, Regilios commented on src/main/java/org/example/univer/dao/mapper/LectureMapper.java
> +        if (!rs.wasNull()) {
если пройдёт пов сем столбцам и ничего не найдёт вернёт null, и проваливаемся для его заполнения как раз.
если ты подразумевал тут использование метода Next, то он не пойдёт, всё упадёт в ошибку т.к. он будет как раз получать null

2024-11-13 16:33 UTC, Regilios commented on README.md
> +<<<<<<< HEAD
test

2024-11-15 05:35 UTC, merged